### ISSUE TITLE
Roadmap V2

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/seo-audits-toolkit#10]
Despite not a lot of features, the project is getting bigger. In order to avoid huge refactors down the line, a few things need to be addressed.
- Moving towards an API driven web app. Implementing REST endpoints for every interaction. This will allow a smooth transition later on to React. Jinja2 is great for small projects, but the objective is to build a fully-featured Seo Audit Toolkit.
- Thinking about using  Distributed Task Queues. This would allow the project to run background jobs and async requests easily. Also, this would increase the scalability of the project.

I'm eager to add new features. But each new feature complexifies the project even more. Taking things slow to avoid huge refactors and bottlenecks.

TODO:
- [x] ~~Completely move towards an API driven webapp~~ 
- [x] Implement Distributed Task queues
- [ ] Add a complete website audit

**Comment by StanGirard** [comment]
Roadmap completely reviewed. Closing for now.

**Comment by kosssi** [comment]
Hello @StanGirard,

This project are awesome <3
I dream to have my own service open source like https://sitechecker.pro with greenit rules ^^

Where is the new roadmap ?

**Comment by StanGirard** [comment]
Hello @kosssi,

Thanks a lot for these warm words. 

I've not worked on the new roadmap yet because I've been working a lot at my actual work 😄 
However, I'll soon think about the new functionalities that I want to add in OSAT in the next version. 
I've looked at some greenit rules and I can add them easily in OSAT. However I'd first like to add some graphs. 

Let me know if you want to participate in the project and I'll onboard you 👍
